package UI;


public enum ViewType {
    START, MANAGERSETUP, SPORTSELECTION, TEAMSELECTION, WELCOME, MENU,
    MATCHSCREEN, LEAGUETABLE, FIXTURE, TRAINING, MYTEAM, MYSQUAD,
    MATCHINTRO, MATCHPLAY, SUBSTITUTION, TACTIC
}
